### ISSUE TITLE
pentf for performance testing?

### ISSUE THREAD

**Issue by bebraw** [boxine/pentf#267]
Hi,

I built some filtering logic within the browser against IndexedDB. To know how well it performs, I would have to benchmark it against an in-memory based solution.

Do you think pentf would be a good fit for this kind of use case? I imagine I would have to run the same test against the same dataset multiple times and then calculate some averages to compare against the different implementations. How would you approach this?

**Comment by marvinhagemeister** [comment]
Not sure if pentf is a good fit for that. We don't have any benchmarking functionality in our code. There is no technical reason not to add it, but I'm wondering if Tachometer sounds like a better fit. It does browser based benchmarking and it's getting more and more speed for measuring performance characteristics of Frontend frameworks.

**Comment by bebraw** [comment]
Thanks! Tachometer looks exactly what I need.

Btw, I am happy to interview you about pentf for the SurviveJS blog if you want more eyes on the tool. I am also experimenting with video a bit these days (live demos). 👍
